{
	"version":"LAYASCENE3D:02",
	"data":{
		"type":"Scene3D",
		"props":{
			"name":"MAX 1",
			"sky":{
				"material":{
					"type":"Laya.SkyBoxMaterial",
					"path":"Assets/Realistic_Drinks/FBX/Materials/Bar_Skybox_mtl2.lmat"
				},
				"mesh":"SkyBox"
			},
			"ambientColor":[
				0.212,
				0.227,
				0.259
			],
			"lightmaps":[],
			"enableFog":false,
			"fogStart":0,
			"fogRange":300,
			"fogColor":[
				0.5,
				0.5,
				0.5
			]
		},
		"child":[
			{
				"type":"Camera",
				"instanceID":0,
				"props":{
					"name":"Main Camera",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						-0.06,
						4.24,
						-3.68
					],
					"rotation":[
						0,
						1,
						0,
						0
					],
					"scale":[
						1,
						1,
						1
					],
					"clearFlag":1,
					"orthographic":false,
					"orthographicVerticalSize":4.6,
					"fieldOfView":60,
					"enableHDR":false,
					"nearPlane":1,
					"farPlane":1000,
					"viewport":[
						0,
						0,
						1,
						1
					],
					"clearColor":[
						0.7686275,
						0.7607844,
						0.764706,
						0.01960784
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":1,
				"props":{
					"name":"GameObject",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						2.98,
						0.31
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						0.7535,
						0.7535,
						0.7535
					]
				},
				"components":[],
				"child":[
					{
						"type":"MeshSprite3D",
						"instanceID":2,
						"props":{
							"name":"樱桃",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								-0.4512276,
								4.80876,
								-0.3903809
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								0.3185136,
								0.3185136,
								0.3185136
							],
							"meshPath":"Assets/Obi/Sample Scenes/SampleResources/Models/CubicSphere-pCube1.lm",
							"enableRender":false,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/Obi/Sample Scenes/SampleResources/Materials/CoarseChecker.lmat"
								}
							]
						},
						"components":[
							{
								"type":"Rigidbody3D",
								"mass":10.5,
								"isKinematic":false,
								"restitution":0,
								"friction":0.5,
								"rollingFriction":0,
								"linearDamping":0,
								"angularDamping":0,
								"overrideGravity":false,
								"gravity":[
									0,
									0,
									0
								],
								"shapes":[
									{
										"type":"SphereColliderShape",
										"center":[
											0,
											0,
											0
										],
										"radius":0.5
									}
								],
								"isTrigger":false
							}
						],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":3,
								"props":{
									"name":"Cherry",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0.094855,
										-0.58579,
										-0.075212
									],
									"rotation":[
										-0.6520569,
										-0.05346518,
										0.05942858,
										0.753944
									],
									"scale":[
										0.9134914,
										0.9135483,
										0.9030119
									],
									"meshPath":"Assets/PerfectIce/Models/Cherry-Cherry.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/PerfectIce/Models/Materials/Cherry_color2.lmat"
										},
										{
											"path":"Assets/PerfectIce/Models/Materials/Cherry_color.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							}
						]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":4,
						"props":{
							"name":"冰块",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0.2282681,
								4.711348,
								-0.4840438
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								0.2611942,
								0.2611942,
								0.2611942
							],
							"meshPath":"Library/unity default resources-Cube.lm",
							"enableRender":false,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/Obi/Sample Scenes/SampleResources/Materials/CoarseChecker.lmat"
								}
							]
						},
						"components":[
							{
								"type":"Rigidbody3D",
								"mass":12,
								"isKinematic":false,
								"restitution":0,
								"friction":0.5,
								"rollingFriction":0,
								"linearDamping":0,
								"angularDamping":0,
								"overrideGravity":false,
								"gravity":[
									0,
									0,
									0
								],
								"shapes":[
									{
										"type":"BoxColliderShape",
										"center":[
											0,
											0,
											0
										],
										"size":[
											1,
											1,
											1
										]
									}
								],
								"isTrigger":false
							}
						],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":5,
								"props":{
									"name":"IceBox1",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										-0.08336378,
										0.1667276,
										-0.05001827
									],
									"rotation":[
										3.090862E-08,
										-0.7071068,
										-0.7071068,
										-3.090862E-08
									],
									"scale":[
										2.500916,
										2.500915,
										2.500915
									],
									"meshPath":"Assets/FBX/IceBox/IceCube01-IceCube.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/FBX/IceBox/Materials/IceCube_d.lmat"
										}
									]
								},
								"components":[
									{
										"type":"Animator",
										"layers":[],
										"cullingMode":0,
										"playOnWake":true
									}
								],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":6,
						"props":{
							"name":"Solver",
							"active":true,
							"isStatic":false,
							"layer":11,
							"position":[
								0,
								-3.954878,
								-0.4114134
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1.32714,
								1.32714,
								1.32714
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"Sprite3D",
						"instanceID":7,
						"props":{
							"name":"Emitter",
							"active":true,
							"isStatic":false,
							"layer":8,
							"position":[
								-1.101526,
								5.268746,
								-0.4114134
							],
							"rotation":[
								0.1889593,
								-0.6813915,
								0.6813915,
								-0.1889593
							],
							"scale":[
								1.327141,
								1.327141,
								1.327141
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":8,
						"props":{
							"name":"触发器",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								-0.1207698,
								3.031188,
								0.02654282
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								2.987791,
								0.1065375,
								1.32714
							],
							"meshPath":"Library/unity default resources-Cube.lm",
							"enableRender":false,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Resources/unity_builtin_extra.lmat"
								}
							]
						},
						"components":[
							{
								"type":"Rigidbody3D",
								"mass":1,
								"isKinematic":false,
								"restitution":0,
								"friction":0.5,
								"rollingFriction":0,
								"linearDamping":0,
								"angularDamping":0,
								"overrideGravity":false,
								"gravity":[
									0,
									0,
									0
								],
								"shapes":[
									{
										"type":"BoxColliderShape",
										"center":[
											0,
											0,
											0
										],
										"size":[
											1,
											1,
											1
										]
									}
								],
								"isTrigger":true
							}
						],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":9,
						"props":{
							"name":"bucket",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0.01999998,
								2.599,
								-0.15
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1.3829,
								5.598406,
								1.3829
							],
							"meshPath":"Assets/Obi/Sample Scenes/SampleResources/Models/bucket-pCylinder1.lm",
							"enableRender":true,
							"materials":[
								{
									"path":"Assets/Wine Liquor Beer and Glassware/Materials/Other/glass 01.lmat"
								}
							]
						},
						"components":[
							{
								"type":"Rigidbody3D",
								"mass":1,
								"isKinematic":true,
								"restitution":0,
								"friction":0.5,
								"rollingFriction":0,
								"linearDamping":0,
								"angularDamping":0,
								"overrideGravity":false,
								"gravity":[
									0,
									0,
									0
								],
								"shapes":[
									{
										"type":"MeshColliderShape",
										"mesh":"Assets/Obi/Sample Scenes/SampleResources/Models/bucket-pCylinder1.lm"
									}
								],
								"isTrigger":false
							}
						],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":10,
						"props":{
							"name":"水杯",
							"active":false,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								10,
								10,
								10
							],
							"meshPath":"Assets/Wine Liquor Beer and Glassware/Models/beer mug-Cylinder.001.lm",
							"enableRender":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/Wine Liquor Beer and Glassware/Materials/Other/glass 02.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"Sprite3D",
						"instanceID":11,
						"props":{
							"name":"Soda Variant",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								-0.29
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								29.171,
								29.171,
								29.171
							]
						},
						"components":[
							{
								"type":"Animator",
								"layers":[],
								"cullingMode":0,
								"playOnWake":true
							}
						],
						"child":[
							{
								"type":"MeshSprite3D",
								"instanceID":12,
								"props":{
									"name":"Glass_Of_Soda",
									"active":false,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										1,
										1,
										1
									],
									"meshPath":"Assets/Realistic_Drinks/FBX/Soda-Glass_Of_Soda.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Realistic_Drinks/FBX/Materials/Glass_mtl.lmat"
										},
										{
											"path":"Assets/Realistic_Drinks/FBX/Materials/Soda_mtl.lmat"
										},
										{
											"path":"Assets/Realistic_Drinks/FBX/Materials/Soda_Head_mtl.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"MeshSprite3D",
								"instanceID":13,
								"props":{
									"name":"Shadow_Mesh",
									"active":false,
									"isStatic":true,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										1,
										1,
										1
									],
									"meshPath":"Assets/Realistic_Drinks/FBX/Soda-Shadow_Mesh.lm",
									"enableRender":true,
									"materials":[
										{
											"path":"Assets/Realistic_Drinks/FBX/Materials/Shadow_Mesh_mtl.lmat"
										}
									]
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":14,
								"props":{
									"name":"Soda_Bubble_Particles_01",
									"active":true,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0.0112,
										0
									],
									"rotation":[
										0,
										-0.8665714,
										0,
										0.4990532
									],
									"scale":[
										15.71627,
										15.71627,
										15.71627
									],
									"isPerformanceMode":true,
									"duration":15,
									"looping":true,
									"prewarm":false,
									"startDelayType":0,
									"startDelay":0,
									"startDelayMin":0,
									"startDelayMax":0,
									"startLifetimeType":2,
									"startLifetimeConstant":15,
									"startLifetimeConstantMin":13,
									"startLifetimeConstantMax":15,
									"startLifetimeGradient":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMin":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMax":{
										"startLifetimes":[]
									},
									"startSpeedType":0,
									"startSpeedConstant":0,
									"startSpeedConstantMin":0,
									"startSpeedConstantMax":0,
									"threeDStartSize":false,
									"startSizeType":0,
									"startSizeConstant":1,
									"startSizeConstantMin":0,
									"startSizeConstantMax":1,
									"startSizeConstantSeparate":[
										1,
										1,
										1
									],
									"startSizeConstantMinSeparate":[
										0,
										0,
										0
									],
									"startSizeConstantMaxSeparate":[
										1,
										1,
										1
									],
									"threeDStartRotation":false,
									"startRotationType":0,
									"startRotationConstant":0,
									"startRotationConstantMin":0,
									"startRotationConstantMax":0,
									"startRotationConstantSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMinSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMaxSeparate":[
										0,
										0,
										0
									],
									"randomizeRotationDirection":0,
									"startColorType":0,
									"startColorConstant":[
										1,
										1,
										1,
										1
									],
									"startColorConstantMin":[
										0,
										0,
										0,
										0
									],
									"startColorConstantMax":[
										1,
										1,
										1,
										1
									],
									"gravity":[
										0,
										-9.81,
										0
									],
									"gravityModifier":0,
									"simulationSpace":1,
									"simulationSpeed":1,
									"scaleMode":1,
									"playOnAwake":true,
									"maxParticles":1,
									"autoRandomSeed":true,
									"randomSeed":0,
									"emission":{
										"enable":true,
										"emissionRate":1,
										"emissionRateTip":"Time",
										"bursts":[]
									},
									"shape":{
										"enable":true,
										"shapeType":3,
										"sphereRadius":1,
										"sphereEmitFromShell":false,
										"sphereRandomDirection":0,
										"hemiSphereRadius":1,
										"hemiSphereEmitFromShell":false,
										"hemiSphereRandomDirection":0,
										"coneAngle":25,
										"coneRadius":1,
										"coneLength":5,
										"coneEmitType":3,
										"coneRandomDirection":0,
										"boxX":0.0001,
										"boxY":0.0001,
										"boxZ":0.0001,
										"boxRandomDirection":0,
										"circleRadius":1,
										"circleArc":360,
										"circleEmitFromEdge":false,
										"circleRandomDirection":0
									},
									"colorOverLifetime":{
										"enable":true,
										"color":{
											"type":1,
											"constant":[
												0,
												0,
												0,
												0
											],
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											},
											"constantMin":[
												0,
												0,
												0,
												0
											],
											"constantMax":[
												0,
												0,
												0,
												0
											],
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											}
										}
									},
									"textureSheetAnimation":{
										"enable":true,
										"tiles":[
											8,
											8
										],
										"type":0,
										"randomRow":true,
										"rowIndex":0,
										"frame":{
											"type":1,
											"constant":0,
											"overTime":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											},
											"constantMin":0,
											"constantMax":0,
											"overTimeMin":{
												"frames":[]
											},
											"overTimeMax":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											}
										},
										"startFrame":{
											"type":0,
											"constant":0,
											"constantMin":0,
											"constantMax":0
										},
										"cycles":6,
										"enableUVChannels":1,
										"enableUVChannelsTip":"-1"
									},
									"renderMode":4,
									"stretchedBillboardCameraSpeedScale":0,
									"stretchedBillboardSpeedScale":0,
									"stretchedBillboardLengthScale":2,
									"sortingFudge":-2000,
									"material":{
										"type":"Laya.ShurikenParticleMaterial",
										"path":"Assets/Realistic_Drinks/FBX/Materials/Soda_Bubbles_Particles.lmat"
									},
									"meshPath":"Assets/Realistic_Drinks/FBX/Soda_Bubbles_Mesh-Soda_Bubbles_Mesh.lm"
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":15,
								"props":{
									"name":"Soda_Bubble_Particles_02",
									"active":false,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										1,
										0,
										1.629207E-07
									],
									"scale":[
										25.07967,
										19.265,
										19.265
									],
									"isPerformanceMode":true,
									"duration":15,
									"looping":true,
									"prewarm":false,
									"startDelayType":0,
									"startDelay":0,
									"startDelayMin":0,
									"startDelayMax":0,
									"startLifetimeType":2,
									"startLifetimeConstant":15,
									"startLifetimeConstantMin":12,
									"startLifetimeConstantMax":15,
									"startLifetimeGradient":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMin":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMax":{
										"startLifetimes":[]
									},
									"startSpeedType":0,
									"startSpeedConstant":0,
									"startSpeedConstantMin":0,
									"startSpeedConstantMax":0,
									"threeDStartSize":false,
									"startSizeType":0,
									"startSizeConstant":1,
									"startSizeConstantMin":0,
									"startSizeConstantMax":1,
									"startSizeConstantSeparate":[
										1,
										1,
										1
									],
									"startSizeConstantMinSeparate":[
										0,
										0,
										0
									],
									"startSizeConstantMaxSeparate":[
										1,
										1,
										1
									],
									"threeDStartRotation":false,
									"startRotationType":0,
									"startRotationConstant":0,
									"startRotationConstantMin":0,
									"startRotationConstantMax":0,
									"startRotationConstantSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMinSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMaxSeparate":[
										0,
										0,
										0
									],
									"randomizeRotationDirection":0,
									"startColorType":0,
									"startColorConstant":[
										1,
										1,
										1,
										1
									],
									"startColorConstantMin":[
										0,
										0,
										0,
										0
									],
									"startColorConstantMax":[
										1,
										1,
										1,
										1
									],
									"gravity":[
										0,
										-9.81,
										0
									],
									"gravityModifier":0,
									"simulationSpace":1,
									"simulationSpeed":1,
									"scaleMode":1,
									"playOnAwake":true,
									"maxParticles":1,
									"autoRandomSeed":true,
									"randomSeed":0,
									"emission":{
										"enable":true,
										"emissionRate":1,
										"emissionRateTip":"Time",
										"bursts":[]
									},
									"shape":{
										"enable":true,
										"shapeType":3,
										"sphereRadius":1,
										"sphereEmitFromShell":false,
										"sphereRandomDirection":0,
										"hemiSphereRadius":1,
										"hemiSphereEmitFromShell":false,
										"hemiSphereRandomDirection":0,
										"coneAngle":25,
										"coneRadius":1,
										"coneLength":5,
										"coneEmitType":3,
										"coneRandomDirection":0,
										"boxX":0.0001,
										"boxY":0.0001,
										"boxZ":0.0001,
										"boxRandomDirection":0,
										"circleRadius":1,
										"circleArc":360,
										"circleEmitFromEdge":false,
										"circleRandomDirection":0
									},
									"colorOverLifetime":{
										"enable":true,
										"color":{
											"type":1,
											"constant":[
												0,
												0,
												0,
												0
											],
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											},
											"constantMin":[
												0,
												0,
												0,
												0
											],
											"constantMax":[
												0,
												0,
												0,
												0
											],
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											}
										}
									},
									"textureSheetAnimation":{
										"enable":true,
										"tiles":[
											8,
											8
										],
										"type":0,
										"randomRow":true,
										"rowIndex":0,
										"frame":{
											"type":1,
											"constant":0,
											"overTime":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											},
											"constantMin":0,
											"constantMax":0,
											"overTimeMin":{
												"frames":[]
											},
											"overTimeMax":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											}
										},
										"startFrame":{
											"type":0,
											"constant":0,
											"constantMin":0,
											"constantMax":0
										},
										"cycles":6,
										"enableUVChannels":1,
										"enableUVChannelsTip":"-1"
									},
									"renderMode":4,
									"stretchedBillboardCameraSpeedScale":0,
									"stretchedBillboardSpeedScale":0,
									"stretchedBillboardLengthScale":2,
									"sortingFudge":-2000,
									"material":{
										"type":"Laya.ShurikenParticleMaterial",
										"path":"Assets/Realistic_Drinks/FBX/Materials/Soda_Bubbles_Particles.lmat"
									},
									"meshPath":"Assets/Realistic_Drinks/FBX/Soda_Bubbles_Mesh-Soda_Bubbles_Mesh.lm"
								},
								"components":[],
								"child":[]
							},
							{
								"type":"ShuriKenParticle3D",
								"instanceID":16,
								"props":{
									"name":"Soda_Bubble_Particles_03",
									"active":false,
									"isStatic":false,
									"layer":0,
									"position":[
										0,
										0,
										-0.1
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										12.94242,
										19.265,
										19.265
									],
									"isPerformanceMode":true,
									"duration":15,
									"looping":true,
									"prewarm":false,
									"startDelayType":0,
									"startDelay":0,
									"startDelayMin":0,
									"startDelayMax":0,
									"startLifetimeType":2,
									"startLifetimeConstant":15,
									"startLifetimeConstantMin":13,
									"startLifetimeConstantMax":15,
									"startLifetimeGradient":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMin":{
										"startLifetimes":[]
									},
									"startLifetimeGradientMax":{
										"startLifetimes":[]
									},
									"startSpeedType":0,
									"startSpeedConstant":0,
									"startSpeedConstantMin":0,
									"startSpeedConstantMax":0,
									"threeDStartSize":false,
									"startSizeType":0,
									"startSizeConstant":1,
									"startSizeConstantMin":0,
									"startSizeConstantMax":1,
									"startSizeConstantSeparate":[
										1,
										1,
										1
									],
									"startSizeConstantMinSeparate":[
										0,
										0,
										0
									],
									"startSizeConstantMaxSeparate":[
										1,
										1,
										1
									],
									"threeDStartRotation":false,
									"startRotationType":0,
									"startRotationConstant":0,
									"startRotationConstantMin":0,
									"startRotationConstantMax":0,
									"startRotationConstantSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMinSeparate":[
										0,
										0,
										0
									],
									"startRotationConstantMaxSeparate":[
										0,
										0,
										0
									],
									"randomizeRotationDirection":0,
									"startColorType":0,
									"startColorConstant":[
										1,
										1,
										1,
										1
									],
									"startColorConstantMin":[
										0,
										0,
										0,
										0
									],
									"startColorConstantMax":[
										1,
										1,
										1,
										1
									],
									"gravity":[
										0,
										-9.81,
										0
									],
									"gravityModifier":0,
									"simulationSpace":1,
									"simulationSpeed":1,
									"scaleMode":1,
									"playOnAwake":true,
									"maxParticles":1,
									"autoRandomSeed":true,
									"randomSeed":0,
									"emission":{
										"enable":true,
										"emissionRate":1,
										"emissionRateTip":"Time",
										"bursts":[]
									},
									"shape":{
										"enable":true,
										"shapeType":3,
										"sphereRadius":1,
										"sphereEmitFromShell":false,
										"sphereRandomDirection":0,
										"hemiSphereRadius":1,
										"hemiSphereEmitFromShell":false,
										"hemiSphereRandomDirection":0,
										"coneAngle":25,
										"coneRadius":1,
										"coneLength":5,
										"coneEmitType":3,
										"coneRandomDirection":0,
										"boxX":0.0001,
										"boxY":0.0001,
										"boxZ":0.0001,
										"boxRandomDirection":0,
										"circleRadius":1,
										"circleArc":360,
										"circleEmitFromEdge":false,
										"circleRandomDirection":0
									},
									"colorOverLifetime":{
										"enable":true,
										"color":{
											"type":1,
											"constant":[
												0,
												0,
												0,
												0
											],
											"gradient":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											},
											"constantMin":[
												0,
												0,
												0,
												0
											],
											"constantMax":[
												0,
												0,
												0,
												0
											],
											"gradientMax":{
												"alphas":[
													{
														"key":0,
														"value":1
													},
													{
														"key":1,
														"value":1
													}
												],
												"rgbs":[
													{
														"key":0,
														"value":[
															0,
															0,
															0
														]
													},
													{
														"key":0.1264668,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.3029374,
														"value":[
															0.3529412,
															0.3529412,
															0.3529412
														]
													},
													{
														"key":0.4764782,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":0.6235294,
														"value":[
															0.682353,
															0.682353,
															0.682353
														]
													},
													{
														"key":0.7058824,
														"value":[
															0.7843137,
															0.7843137,
															0.7843137
														]
													},
													{
														"key":0.8735332,
														"value":[
															1,
															1,
															1
														]
													},
													{
														"key":1,
														"value":[
															0,
															0,
															0
														]
													}
												]
											}
										}
									},
									"textureSheetAnimation":{
										"enable":true,
										"tiles":[
											8,
											8
										],
										"type":0,
										"randomRow":true,
										"rowIndex":0,
										"frame":{
											"type":1,
											"constant":0,
											"overTime":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											},
											"constantMin":0,
											"constantMax":0,
											"overTimeMin":{
												"frames":[]
											},
											"overTimeMax":{
												"frames":[
													{
														"key":0,
														"value":0
													},
													{
														"key":1,
														"value":63.9936
													}
												]
											}
										},
										"startFrame":{
											"type":0,
											"constant":0,
											"constantMin":0,
											"constantMax":0
										},
										"cycles":6,
										"enableUVChannels":1,
										"enableUVChannelsTip":"-1"
									},
									"renderMode":4,
									"stretchedBillboardCameraSpeedScale":0,
									"stretchedBillboardSpeedScale":0,
									"stretchedBillboardLengthScale":2,
									"sortingFudge":-2000,
									"material":{
										"type":"Laya.ShurikenParticleMaterial",
										"path":"Assets/Realistic_Drinks/FBX/Materials/Soda_Bubbles_Particles.lmat"
									},
									"meshPath":"Assets/Realistic_Drinks/FBX/Soda_Bubbles_Mesh-Soda_Bubbles_Mesh.lm"
								},
								"components":[],
								"child":[]
							}
						]
					}
				]
			},
			{
				"type":"DirectionLight",
				"instanceID":17,
				"props":{
					"name":"Directional Light",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						3,
						0
					],
					"rotation":[
						0.04826273,
						0.8449536,
						0.5302501,
						-0.05058743
					],
					"scale":[
						1,
						1,
						1
					],
					"intensity":1,
					"lightmapBakedType":0,
					"color":[
						1,
						0.9568627,
						0.8392157
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":18,
				"props":{
					"name":"Emitter (1)",
					"active":false,
					"isStatic":false,
					"layer":11,
					"position":[
						-0.44,
						4.6,
						0
					],
					"rotation":[
						-0.2282782,
						-0.6692452,
						0.6692452,
						0.2282781
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"MeshSprite3D",
				"instanceID":19,
				"props":{
					"name":"Cube",
					"active":false,
					"isStatic":false,
					"layer":0,
					"position":[
						-0.53,
						3.76,
						0
					],
					"rotation":[
						0,
						0,
						-0.2420737,
						-0.9702579
					],
					"scale":[
						2.909977,
						0.1606018,
						1
					],
					"meshPath":"Library/unity default resources-Cube.lm",
					"enableRender":true,
					"materials":[
						{
							"path":"Assets/Obi/Sample Scenes/SampleResources/Materials/Walls.lmat"
						}
					]
				},
				"components":[
					{
						"type":"PhysicsCollider",
						"restitution":0,
						"friction":0.5,
						"rollingFriction":0,
						"shapes":[
							{
								"type":"BoxColliderShape",
								"center":[
									0,
									0,
									0
								],
								"size":[
									1,
									1,
									1
								]
							}
						],
						"isTrigger":false
					}
				],
				"child":[]
			},
			{
				"type":"MeshSprite3D",
				"instanceID":20,
				"props":{
					"name":"Cube (1)",
					"active":false,
					"isStatic":false,
					"layer":0,
					"position":[
						-2.98,
						2.55,
						0
					],
					"rotation":[
						0,
						0,
						0.3577804,
						-0.9338058
					],
					"scale":[
						2.083253,
						0.1606018,
						1
					],
					"meshPath":"Library/unity default resources-Cube.lm",
					"enableRender":true,
					"materials":[
						{
							"path":"Assets/Obi/Sample Scenes/SampleResources/Materials/Walls.lmat"
						}
					]
				},
				"components":[
					{
						"type":"PhysicsCollider",
						"restitution":0,
						"friction":0.5,
						"rollingFriction":0,
						"shapes":[
							{
								"type":"BoxColliderShape",
								"center":[
									0,
									0,
									0
								],
								"size":[
									1,
									1,
									1
								]
							}
						],
						"isTrigger":false
					}
				],
				"child":[]
			},
			{
				"type":"MeshSprite3D",
				"instanceID":21,
				"props":{
					"name":"TestEnvironment",
					"active":false,
					"isStatic":false,
					"layer":0,
					"position":[
						-0.33,
						2.3493,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						0.1693062,
						0.1693062,
						0.1693062
					],
					"meshPath":"Assets/Obi/Sample Scenes/SampleResources/Models/TestEnvironment-pCube1.lm",
					"enableRender":true,
					"materials":[
						{
							"type":"Laya.BlinnPhongMaterial",
							"path":"Assets/Obi/Sample Scenes/SampleResources/Materials/CoarseChecker.lmat"
						}
					]
				},
				"components":[
					{
						"type":"PhysicsCollider",
						"restitution":0,
						"friction":0.5,
						"rollingFriction":0,
						"shapes":[
							{
								"type":"MeshColliderShape",
								"mesh":"Assets/Obi/Sample Scenes/SampleResources/Models/TestEnvironment-pCube1.lm"
							}
						],
						"isTrigger":false
					}
				],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":22,
				"props":{
					"name":"Canvas",
					"active":true,
					"isStatic":false,
					"layer":5,
					"position":[
						-344,
						156,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						0.86,
						0.86,
						0.86
					]
				},
				"components":[],
				"child":[
					{
						"type":"Sprite3D",
						"instanceID":23,
						"props":{
							"name":"Button",
							"active":true,
							"isStatic":false,
							"layer":5,
							"position":[
								-372.9,
								158.9953,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[
							{
								"type":"Sprite3D",
								"instanceID":24,
								"props":{
									"name":"Text",
									"active":false,
									"isStatic":false,
									"layer":5,
									"position":[
										0,
										0,
										0
									],
									"rotation":[
										0,
										0,
										0,
										-1
									],
									"scale":[
										1,
										1,
										1
									]
								},
								"components":[],
								"child":[]
							}
						]
					},
					{
						"type":"Sprite3D",
						"instanceID":25,
						"props":{
							"name":"Text",
							"active":false,
							"isStatic":false,
							"layer":5,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								1,
								1,
								1
							]
						},
						"components":[],
						"child":[]
					}
				]
			},
			{
				"type":"Sprite3D",
				"instanceID":26,
				"props":{
					"name":"EventSystem",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":27,
				"props":{
					"name":"Solver备份",
					"active":false,
					"isStatic":false,
					"layer":11,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":28,
				"props":{
					"name":"水倒进杯子里",
					"active":false,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":29,
				"props":{
					"name":"冰块放进水里",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						0,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[]
			}
		]
	}
}